const GET_PEOPLES_LIST = 'peopleTypes@GET_PEOPLE';
const SET_PEOPLE_ADDRESS = 'peopleTypes@SET_PEOPLE_ADDRESS';
const TOGGLE_STATUS = 'peopletype@TOGGLE_STATUS'

export {
    GET_PEOPLES_LIST,
    SET_PEOPLE_ADDRESS,
    TOGGLE_STATUS
}